#let default = (
    style: (
        variant: "iec",
        scale: (x: 1.0, y: 1.0),
        stroke: (
            thickness: .8pt,
            paint: black,
            join: "miter",
            cap: "butt",
            miter-limit: 4,
            dash: none,
        ),
        background: (
            fill: none,
        ),
        foreground: (
            fill: white,
        ),
        label: (
            scale: auto,
            content: none,
            distance: 7pt,
            anchor: "north",
        ),
        node: (
            stroke: (
                thickness: .4pt,
                paint: black,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: black,
            nofill: white,
            radius: .05,
        ),
        wire: (
            stroke: (
                thickness: .5pt,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
        ),
        arrow: (
            variant: ">",
            scale: 1.0,
            stroke: (
                thickness: 1pt,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            variable: (
                variant: auto,
                scale: 1.0,
                stroke: (
                    thickness: auto,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                length: 40pt,
                angle: 55deg,
                ratio: (0.5, 0.5),
            ),
            radiation: (
                variant: auto,
                scale: 0.8,
                stroke: (
                    thickness: 0.55pt,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                distance: 3pt,
                length: 12pt,
                angle: -120deg,
                reversed: false,
            ),
            adjustable: (
                variant: auto,
                scale: 1.0,
                stroke: (
                    thickness: auto,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                length: 0.8,
            ),
        ),
        decoration: (
            variant: ">",
            scale: 1.0,
            stroke: (
                thickness: 1pt,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            content: none,
            distance: 9pt,
            position: (x: "east", y: "north"),
            anchor: "north-east",
            invert: false,
            current: (
                variant: auto,
                scale: 1.0,
                stroke: (
                    thickness: auto,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                content: auto,
                distance: auto,
                position: (x: auto, y: auto),
                anchor: auto,
                invert: auto,
            ),
            flow: (
                variant: auto,
                scale: 1.0,
                stroke: (
                    thickness: 0.55pt,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                content: auto,
                distance: auto,
                position: (x: auto, y: auto),
                anchor: auto,
                invert: auto,
                length: 0.7,
                indent: 0.2,
                label-ratio: 50%,
            ),
            voltage: (
                variant: auto,
                scale: 1.0,
                stroke: (
                    thickness: auto,
                    paint: auto,
                    join: auto,
                    cap: auto,
                    miter-limit: auto,
                    dash: auto,
                ),
                content: auto,
                distance: auto,
                position: (x: auto, y: auto),
                anchor: auto,
                invert: auto,
                start: (-.4, .1),
                end: (.4, .1),
                center: (0, .3),
            ),
        ),
        debug: (
            stroke: (
                thickness: .2pt,
                paint: red,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            enabled: false,
            radius: .7pt,
            angle: -30deg,
            shift: 3pt,
            inset: 1pt,
            font: 3pt,
            fill: red,
        ),
        // Components
        capacitor: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: none,
            width: .8,
            distance: .25,
            radius: 0.6,
            angle: 40deg,
        ),
        diode: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: .3,
            width: .25,
            tunnel-length: .11,
        ),
        opamp: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            width: 1.8,
            height: 1.75,
            padding: .28,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .45,
        ),
        switch: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            width: .8,
            angle: 35deg,
        ),
        fuse: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            width: .88,
            height: .88 / 2.4,
            asymmetry: 25%,
        ),
        ground: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: 0.22,
            distance: 0.28,
        ),
        frame: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            number: 3,
            width: 0.46,
            angle: 20deg,
            depth: 0.25,
            distance: 0.28,
        ),
        earth: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            width: .53,
            delta: .09,
            spacing: .11,
            distance: .28,
        ),
        vcc: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            angle: 35deg,
            radius: .4,
            distance: .6,
        ),
        vee: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            angle: 35deg,
            radius: .4,
            distance: .6,
        ),
        inductor: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: black,
            width: 1.41,
            height: 1.41 / 3,
            bumps: 3,
        ),
        resistor: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            width: 1.41,
            height: .47,
            zigs: 3,
        ),
        vsource: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: .53,
            padding: .25,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .07,
        ),
        isource: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: .53,
            padding: .25,
            arrow-scale: 1,
        ),
        acmotor: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: .49,
            magnet-width: 1.23,
            magnet-height: 1.23 / 4,
        ),
        dcmotor: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: white,
            radius: .49,
            magnet-width: 1.23,
            magnet-height: 1.23 / 4,
        ),
        bjt: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            radius: .65,
            base-height: .6,
            base-distance: .12,
            aperture: 50deg,
        ),
        mosfet: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
        antenna: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            fill: none,
            distance: 0.8,
            spacing: 0.35,
            length: 0.5,
        ),
        transformer: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            radius: 0.35,
            distance: 0.45,
        ),
        converter: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            width: 1.7,
            height: 0.7,
            arrow-width: 0.4,
            label: (
                align: "center",
            ),
        ),
        mcu: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: auto,
                paint: auto,
                join: auto,
                cap: auto,
                miter-limit: auto,
                dash: auto,
            ),
            width: 3,
            min-height: 1,
            padding: 0.2,
            spacing: 0.4,
        ),
    ),
)
